### ISSUE TITLE
Good to interpret TEXINPUTS value?

### ISSUE THREAD

**Issue by kuroky49** [norbusan/ptex2pdf#1]
Usual TeX systems are controlled under the TEXINPUTS value, but ptex2pdf doesn't.
How should it be?

Please see
http://oku.edu.mie-u.ac.jp/tex/mod/forum/discuss.php?d=1560#p8884

**Comment by norbusan** [comment]
Fixed in 0.7 which I have pushed just now, and uploaded to CTAN, and included in TeX Live. Should work in TeX Live starting from tomorrow.
