### ISSUE TITLE
Interpretending .ltx extention as a LaTeX file

### ISSUE THREAD

**Issue by kuroky49** [norbusan/ptex2pdf#3]
ptex2pdf might add .tex extention to the given filename.  However, for example, if we want to distinguish TeX format source and LaTeX format source by extention, say, .tex and .ltx, respectively, then the current specification makes troubles.  Could ptex2pdf
(1) search the file first by the original name first then secondly by the name with .tex extention, or
(2) search the file by the name with both .tex and .ltx extention?

**Comment by norbusan** [comment]
Hi Kuroki-san,

thanks, I have reworked the filename checking code to first search for the passed-in filename as is, if not found try .tex extension, then if not found try .ltx extension, then give up.

If you can give the current script here a test-run, that would be great. On my computer it worked as expected (or at least, as _I_ expected ;-)

**Comment by kuroky49** [comment]
Thank you for your immediate improvements.  Your interpretation is truly expected (thanks for merging both the ways I have supposed).  I've just tested several cases and they are all succeeded.

One point, then, the error message was shown as follows:
  This is ptex2pdf[.lua] version 0.7.
  File cannot be found with kpathsea:     main3(.tex, .ltx)
It includes two kinds of puctuations---parentheses and brackets---with the same meaning: the contents could be omitted.  I think brackets rather than parentheses are good for this purpose in this context.

**Comment by norbusan** [comment]
Thanks, changed that now, too. Anything else, or can I upload this version to CTAN?

**Comment by kuroky49** [comment]
Thanks.  I think it is good to upload any distributions.
